apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: flux-system
spec:
  repo: https://dl.gitea.com/charts/
  chart: gitea
  version: 9.5.1
  targetNamespace: gitea
  createNamespace: true
  valuesContent: |-
      gitea:
        admin: 
          existingSecret: gitea-admin-secret
      ingress: 
        enabled: true
        className: nginx
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: gitea.k3s.homelab.hack
            paths:
              - path: /
                pathType: Prefix
        tls: 
          - secretName: gitea-local-tls
            hosts:
              - gitea.k3s.homelab.hack