apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: gitea
  namespace: flux-system
spec:
  repo: https://dl.gitea.com/charts/
  chart: gitea
  version: 9.5.1
  targetNamespace: gitea
  createNamespace: true
