apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
  namespace: external-secrets
spec:
  provider:
    fake:
      data:
        - key: "/foo/bar"
          value: "HELLO1"
          version: "v1"
        - key: "/foo/bar"
          value: "HELLO2"
          version: "v2"
        - key: "/foo/baz"
          valueMap:
            foo: example
            other: thing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: secret-to-be-created
  data:
    - secretKey: foo_bar
      remoteRef:
        key: /foo/bar
        version: v1
  dataFrom:
    - extract:
        key: /foo/baz