---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  repo: https://charts.external-secrets.io
  chart: external-secrets
  version: 0.9.11
  targetNamespace: external-secrets
  createNamespace: true
#  valuesContent: |-
#    installCRDs: true