apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./cluster-components
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: homelab
  timeout: 3m0s
  wait: true
