apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-stack
  namespace: flux-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 56.0.1
  targetNamespace: monitoring
  createNamespace: true
  valuesContent: |-
    prometheus: 
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - prometheus.k3s.homelab.hack
        paths:
          - /
        tls: 
          - secretName: prometheus-local-tls
            hosts:
              - prometheus.k3s.homelab.hack